import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from "react";
import axios from 'axios';

export default function Home() {
  const CLIENT_ID = "982f299ad71d4ab19ed41e91758577dc"
  const REDIRECT_URI = "http://localhost:3000"
  const AUTH_ENDPOINT = "https://accounts.spotify.com/authorize"
  const RESPONSE_TYPE = "token"

  const [token, setToken] = useState(null)
  const [profile, setProfile] = useState(null)

  useEffect(() => {
    const hash = window.location.hash
    let token = window.localStorage.getItem("token")

    // getToken()
    if (!token && hash) {
      token = hash.substring(1).split("&").find(elem => elem.startsWith("access_token")).split("=")[1]

      window.location.hash = ""
      window.localStorage.setItem("token", token)
    }

    setToken(token)

    const fetchData = async () => {
      try {
        const { data } = await axios.get("https://api.spotify.com/v1/me", {
          headers: {
            Authorization: `Bearer ${token}`
          },
        })
        setProfile(data)
      } catch (error) {
        console.error(error)
      }
    }
    fetchData()
  }, [])

  const logout = () => {
    setToken("")
    window.localStorage.removeItem("token")
  }

  return (
    <>
      <Head>
        <title>🚀 Spotify Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Appheader}>
        <div className="flex flex-col m-20 justify-center items-center">
          <h1 className="font-bold text-3xl">🚀 Spotify Profile</h1>
          <br />
          {
            !token ?
              <button className="bg-green-500 hover:bg-green-700 text-white font-semibold py-2 px-4 rounded-lg shadow">
                <a href={`${AUTH_ENDPOINT}?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&response_type=${RESPONSE_TYPE}`}>
                  <p className='text-xl'>Connect Spotify</p>
                </a>
              </button>
              :
              <button onClick={logout} className="bg-red-700 hover:bg-red-900 text-gray-100 font-semibold py-2 px-4 rounded-lg shadow">
                <p className='text-xl'>Logout</p>
              </button>
          }
          <div className='m-5'></div>
          {
            token ?
              profile &&
              <div>
                {
                  profile.images.length &&
                  profile.images[0].url &&
                  <img className='rounded-full' src={profile.images[0].url} alt='Avatar' />
                }
                <div className='m-5'></div>
                <h1 className='font-bold text-5xl text-center'>
                  {profile.display_name}
                </h1>
                <div className='m-5'></div>
                <p className='font-semibold text-xl text-center'>
                  {profile.followers.total} Followers
                </p>
              </div>
              :
              <div>
                {/* Empty Div */}
              </div>
          }
          <br />
        </div>
      </main>
    </>
  )
}
